Arm32 support
ARM-software/bbr-acs pull request #8
Opened 2022-04-12 09:26 UTC by cpriouzeau

- Patch of EDK2 for ARM32 support
- Adaptation of list of BBR SCT

2022-05-04 07:55 UTC, etienne-lms commented
Hello @cpriouzeau and all,
Base on this P-R, i've created https://github.com/ARM-software/bbr-acs/pull/9 and  https://github.com/ARM-software/bbr-acs/pull/10, as proposals for discussions around 32bit architecture support in bbr-acs.

P-R #9 targets a common BBR_SCT.dsc file for AARCH64 and ARM.
P-R #10 targets a common build_bbr.sh script and prevents need for your commit "ARM32 support: EDK2: patch for ARM32 support".
Dear maintainers, do these changes make sense to you?

These 2 P-Rs do not cover all required changes in other build scripts (`build-sct.sh`, `buildf-wts.sh`, `build-uefi-apps.sh`) for toolchain/architecture selection. I think these could be factorized with related changes in https://github.com/ARM-software/arm-systemready/pull/25.

2022-06-21 16:44 UTC, edhay commented on common/scripts/build-sct.sh
> +. $TOP_DIR/../../common/config/common_config.cfg
Please refactor the changes in file to a new file common/scripts/build-sct-arm.sh

The original file common/scripts/build-sct.sh shall be unmodified.

2022-06-21 16:44 UTC, edhay commented on common/scripts/build-uefi-apps.sh
Please refactor the changes in file to a new file common/scripts/build-uefi-apps-arm.sh

The original file common/scripts/build-uefi-apps.sh shall be unmodified.

2022-06-21 16:45 UTC, edhay requested changes
Please check my comments on refactoring. This is to minimize the impact on the 64-bit ACS

2022-06-22 13:28 UTC, vstehle commented on common/scripts/build-uefi-apps.sh
> +        else
Indentation does not seem to match the opening if.

2022-06-22 16:15 UTC, etienne-lms commented
Can close this P-R as superseded by https://github.com/ARM-software/bbr-acs/pull/11.

2022-07-01 15:11 UTC, closed without merging